---

int_prof:
 - leaf101
 - leaf102


leaf_prof:
 - leaf101
 - leaf102


node_map:
  - {leaf_profiles: 'leaf101', leaf: 'leaf101', node: '101', from: '101', to: '101'}
  - {leaf_profiles: 'leaf102', leaf: 'leaf102', node: '102', from: '102', to: '102'}


leaf_map:
  - {int_profiles: 'leaf101', leaf_profiles: 'leaf101'}
  - {int_profiles: 'leaf102', leaf_profiles: 'leaf102'}
