---
- name: ansible main for aci deployments
  hosts: apic
  gather_facts: no
  connection: local

#import and execute playbooks for aci deployment resources
# - import_playbook: ./access_policies/leaf_int_profiles.yml
# - import_playbook: ./access_policies/vpc_domain.yml
# - import_playbook: ./ap/ap.yml
# - import_playbook: ./assign_ports/assign_ports.yml
# - import_playbook: ./bds/bds.yml
# - import_playbook: ./contracts/contracts.yml
# - import_playbook: ./epgs/epgs.yml
# - import_playbook: ./global/global.yml
# - import_playbook: ./gw_cut/gw_cut.yml
# - import_playbook: ./rest/rest.yml
# - import_playbook: ./snapshot/snapshot.yml
# - import_playbook: ./static_bind/static_bind.yml
- import_playbook: ./tenant/tenant.yml
# - import_playbook: ./oob_mgmt/oob_mgmt.yml