---
- name: aci deploy app profile template
  hosts: apic
  connection: local
  gather_facts: no

#aci deploy a single ap
  tasks:
      - name: add prod app profile
        aci_ap:
         host: "{{ inventory_hostname }}"
         username: "{{ username }}"
         password: "{{ password }}"
         validate_certs: no 
         tenant: tenant1
         ap: ap1
         description: Production App Profile
         state: present

#aci deploy a list of app profiles with a loop
      - name: add prod app profile
        aci_ap:
         host: "{{ inventory_hostname }}"
         username: "{{ username }}"
         password: "{{ password }}"
         validate_certs: no 
         tenant: tenant1
         ap: "{{ item }}"
         description: sling a bunch of app profiles
         state: present
        with_items: "{{ aps }}"



